### ISSUE TITLE
How to write the image

### ISSUE THREAD

**Issue by PetersPlace** [TakissX/HLK-RM04#2]
Hello,

I can access my HLK-RM04 to the serial port, in the menu i can choose option 2 load by TFTP.
This runs fine, but the HLK does not accept the image the end

Do i need to change other settings in the option 4 setenv commands?
Do i need to set the memory points

**Comment by TakissX** [comment]
The easiest way is with a universal programmer, '**without removing the eeprom**'

**Comment by TakissX** [comment]
**Restore original firmware**

With a bin file processor we get the backup flash HLK_RM04 W25Q32.bin
u-boot + u-boot-env and kernel + rootfs in two files.

We install the u-boot from here https://github.com/smarpl/hlk-rm04_u-boot because it also has UART media image installation by pressing '0'.

Steps after successfully installing u-boot.

1. Install the file we have created by editing the backup flash HLK_RM04 W25Q32.bin kernel + rootfs. With UART “pressing 0” or TFTP “pressing 2”.

2. Install the file we have created by editing the backup flash HLK_RM04 W25Q32.bin u-boot. With UART “pressing 7” or TFTP “pressing 9”.
